#!/usr/bin/env bash
#
# Harness bootstrap — install the multi-agent harness into any project.
#
#   bash harness.sh                      # install into the current directory
#   bash harness.sh /path/to/project     # install into another project
#   bash harness.sh . --install-tools    # also install CodeGraph / RTK / Caveman
#   bash harness.sh . --profile python-web --force
#
# Idempotent: safe to re-run to pick up harness updates. Existing files are
# never clobbered unless --force is passed (profile.env only).
#
# Flags:
#   --profile <name>   node-web | python-web | flutter | go | generic (default: auto)
#   --install-tools    let the optimizer run third-party installers
#   --no-optimize      skip the token-optimization layer entirely
#   --force            regenerate .harness/profile.env from the template
#   --no-run           scaffold only; do not run doctor at the end

set -euo pipefail

HARNESS_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
YELLOW=$'\033[33m'; BLUE=$'\033[34m'; RESET=$'\033[0m'
[[ -t 1 ]] || { BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; BLUE=""; RESET=""; }

ok()   { printf '%s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
warn() { printf '%s!%s %s\n' "$YELLOW" "$RESET" "$1"; }
info() { printf '%s·%s %s\n' "$BLUE" "$RESET" "$1"; }
die()  { printf '%s✗%s %s\n' "$RED" "$RESET" "$1" >&2; exit 1; }

# --- arguments -------------------------------------------------------------

TARGET=""
PROFILE="auto"
INSTALL_TOOLS=""
OPTIMIZE="yes"
FORCE=""
RUN_DOCTOR="yes"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)        PROFILE="${2:?--profile needs a value}"; shift 2 ;;
    --profile=*)      PROFILE="${1#*=}"; shift ;;
    --install-tools)  INSTALL_TOOLS="--install"; shift ;;
    --no-optimize)    OPTIMIZE=""; shift ;;
    --force)          FORCE="--force"; shift ;;
    --no-run)         RUN_DOCTOR=""; shift ;;
    -h|--help)        sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*)               die "Unknown flag: $1" ;;
    *)                TARGET="$1"; shift ;;
  esac
done

TARGET="${TARGET:-$PWD}"
[[ -d "$TARGET" ]] || die "Not a directory: $TARGET"
TARGET="$(cd "$TARGET" && pwd)"

command -v python3 >/dev/null 2>&1 || die "python3 is required (the harness CLI is a single python3 script with no dependencies)"

printf '\n%sHarness bootstrap%s\n' "$BOLD" "$RESET"
info "Source: $HARNESS_SRC"
info "Target: $TARGET"

[[ "$HARNESS_SRC" == "$TARGET" ]] && die "Refusing to install the harness into its own source repository."

# --- 1. copy the harness ---------------------------------------------------

DEST="$TARGET/.harness"
mkdir -p "$DEST"

# Everything except generated state, so re-running upgrades in place.
for dir in bin agents commands hooks profiles templates; do
  rm -rf "${DEST:?}/$dir"
  cp -R "$HARNESS_SRC/harness/$dir" "$DEST/$dir"
done
chmod +x "$DEST/bin/harness" "$DEST/bin/optimize.sh"
ok "Copied harness into .harness/"

# --- 2. root shim ----------------------------------------------------------

cat > "$TARGET/harness" <<'SHIM'
#!/usr/bin/env bash
# Harness entry point. Generated by harness.sh — safe to regenerate.
exec python3 "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.harness/bin/harness" "$@"
SHIM
chmod +x "$TARGET/harness"
ok "Created ./harness"

# --- 3. scaffold state, agents, commands, hooks ----------------------------

printf '\n'
( cd "$TARGET" && python3 .harness/bin/harness init --profile "$PROFILE" $FORCE ) \
  || die "harness init failed"

# --- 4. token optimization layer ------------------------------------------

if [[ -n "$OPTIMIZE" ]]; then
  bash "$DEST/bin/optimize.sh" "$TARGET" "$INSTALL_TOOLS" || warn "Optimizer reported problems (non-fatal)"
fi

# --- 5. git hook: keep the CodeGraph index current after every commit ------
# Only if CodeGraph is on PATH and this is a git repo. Idempotent: skipped if
# a post-commit hook already syncs CodeGraph; appended if one exists for other
# reasons; installed fresh otherwise. Prefers Husky (.husky/) when present,
# falls back to the plain .git/hooks/ dir.

if command -v codegraph >/dev/null 2>&1 && git -C "$TARGET" rev-parse --git-dir >/dev/null 2>&1; then
  if [[ -d "$TARGET/.husky" ]]; then
    HOOK_DEST="$TARGET/.husky/post-commit"
  else
    HOOK_DEST="$TARGET/.git/hooks/post-commit"
  fi
  if [[ -f "$HOOK_DEST" ]] && grep -q "codegraph sync" "$HOOK_DEST" 2>/dev/null; then
    info "post-commit hook already syncs CodeGraph — skipped"
  elif [[ -f "$HOOK_DEST" ]]; then
    { printf '\n'; cat "$DEST/templates/post-commit"; } >> "$HOOK_DEST"
    ok "Appended CodeGraph sync to existing $HOOK_DEST"
  else
    cp "$DEST/templates/post-commit" "$HOOK_DEST"
    ok "Installed post-commit hook: CodeGraph sync ($HOOK_DEST)"
  fi
  chmod +x "$HOOK_DEST"
fi

# --- 6. verify the install -------------------------------------------------

if [[ -n "$RUN_DOCTOR" ]]; then
  printf '\n'
  ( cd "$TARGET" && ./harness doctor --quick ) || warn "Doctor found problems — see above"
fi

# --- done ------------------------------------------------------------------

cat <<EOF

${BOLD}Installed.${RESET}

  ${DIM}Edit the stack commands if the detection got anything wrong:${RESET}
  .harness/profile.env

  ${DIM}Then define your scope and run one feature end to end:${RESET}
  feature_list.json
  ./harness status
  ./harness feature next

  ${DIM}In Claude Code:${RESET}
  /feature          run one feature through implementer → reviewer → testers → gate
  /qa               test existing code (automated + exploratory with screenshots)
  /gate             what is blocking the active feature
  /harness-status   one-screen summary

EOF
