/**
 * Harness Playwright config — generated by `harness init`. Safe to delete and
 * regenerate; do not hand-edit unless you also update the harness.
 *
 * It extends your project's own playwright config and only changes what the
 * harness needs:
 *   - screenshots and traces are always on, so every test leaves evidence
 *   - all artifacts land in the dated report folder for this run
 *
 * Run it through the harness so HARNESS_REPORT_DIR is set:
 *     ./harness verify        # full suite
 *     ./harness explore <id>  # exploratory walkthrough
 */
import { defineConfig } from '@playwright/test';
import path from 'node:path';
import base from '__BASE_CONFIG__';

const root = path.resolve(import.meta.dirname, '..');

// The harness exports this before every run. The fallback keeps a bare
// `npx playwright test --config .harness/playwright.harness.ts` usable.
const reportDir = process.env.HARNESS_REPORT_DIR
  ? path.resolve(process.env.HARNESS_REPORT_DIR)
  : path.join(root, 'test-reports', 'adhoc');

const baseConfig = base as Record<string, any>;

// testDir in the base config is relative to the base config file, which lives
// one level up from here — resolve it against the repo root, not against .harness/.
const baseTestDir: string = baseConfig.testDir ?? 'e2e';
const testDir = path.isAbsolute(baseTestDir)
  ? baseTestDir
  : path.resolve(root, baseTestDir);

// Same story for webServer: its cwd defaults to the config file's directory.
const webServer = baseConfig.webServer
  ? Array.isArray(baseConfig.webServer)
    ? baseConfig.webServer.map((server: any) => ({ cwd: root, ...server }))
    : { cwd: root, ...baseConfig.webServer }
  : undefined;

export default defineConfig({
  ...baseConfig,
  testDir,
  webServer,
  outputDir: path.join(reportDir, 'artifacts'),
  use: {
    ...(baseConfig.use ?? {}),
    screenshot: 'on',
    trace: 'on',
    video: 'retain-on-failure',
  },
  reporter: [
    ['list'],
    ['html', { outputFolder: path.join(reportDir, 'playwright-report'), open: 'never' }],
    ['json', { outputFile: path.join(reportDir, 'playwright-results.json') }],
  ],
});
